# Generated by Django 3.2.5 on 2021-07-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='queries',
            field=models.CharField(max_length=500),
        ),
    ]
