# Generated by Django 3.2.5 on 2021-07-16 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dto', '0007_alter_signin_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signin',
        ),
    ]
