# Generated by Django 3.2.5 on 2021-07-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dto', '0008_delete_signin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Four',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50, null=True)),
                ('regno', models.CharField(max_length=50, null=True)),
                ('catagory', models.CharField(max_length=50, null=True)),
                ('amt', models.IntegerField()),
                ('adress', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=10, null=True)),
                ('state', models.CharField(max_length=10, null=True)),
                ('zip', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Nongear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50, null=True)),
                ('regno', models.CharField(max_length=50, null=True)),
                ('catagory', models.CharField(max_length=50, null=True)),
                ('amt', models.IntegerField()),
                ('adress', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=10, null=True)),
                ('state', models.CharField(max_length=10, null=True)),
                ('zip', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Two',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=50, null=True)),
                ('regno', models.CharField(max_length=50, null=True)),
                ('catagory', models.CharField(max_length=50, null=True)),
                ('amt', models.IntegerField()),
                ('adress', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=10, null=True)),
                ('state', models.CharField(max_length=10, null=True)),
                ('zip', models.IntegerField()),
            ],
        ),
    ]
