# Generated by Django 3.2.5 on 2021-07-19 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dto', '0010_auto_20210716_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='four',
            name='catagory',
        ),
        migrations.RemoveField(
            model_name='nongear',
            name='catagory',
        ),
        migrations.RemoveField(
            model_name='two',
            name='catagory',
        ),
    ]
