# Generated by Django 3.2.5 on 2021-07-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dto', '0011_auto_20210719_1908'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=10, null=True)),
                ('phone', models.IntegerField()),
                ('vtype', models.CharField(max_length=5, null=True)),
                ('gender', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
