# Generated by Django 3.2.5 on 2021-07-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dto', '0012_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='four',
            name='chalantype',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='nongear',
            name='chalantype',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='two',
            name='chalantype',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
