# Generated by Django 3.2.5 on 2021-07-26 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dto', '0015_auto_20210726_1342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apply',
        ),
        migrations.RemoveField(
            model_name='four',
            name='city',
        ),
        migrations.RemoveField(
            model_name='four',
            name='state',
        ),
        migrations.RemoveField(
            model_name='nongear',
            name='city',
        ),
        migrations.RemoveField(
            model_name='nongear',
            name='state',
        ),
        migrations.RemoveField(
            model_name='two',
            name='city',
        ),
        migrations.RemoveField(
            model_name='two',
            name='state',
        ),
    ]
