# Generated by Django 3.2.5 on 2021-07-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dto', '0023_auto_20210727_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='four',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='nongear',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='two',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
