# Generated by Django 3.2.5 on 2021-07-28 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dto', '0024_auto_20210727_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='four',
            name='zip',
        ),
        migrations.RemoveField(
            model_name='nongear',
            name='zip',
        ),
        migrations.RemoveField(
            model_name='two',
            name='zip',
        ),
    ]
