# Generated by Django 3.2.5 on 2021-08-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dto', '0027_fileupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=20, null=True)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('matter', models.TextField()),
            ],
        ),
    ]
