# Generated by Django 3.2.5 on 2021-08-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dto', '0028_grievance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievance',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
