# Generated by Django 3.2.5 on 2021-08-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dto', '0030_auto_20210803_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
